---
# tasks file for aws_vpc
- name: Ready up the {{ aws_vpc_cidr_block }} VPC
  register: "{{ aws_vpc_register_as }}"
  with_nested:
    - aws_vpc_subnets
    - aws_vpc_igw_enabled_subnets
  ec2_vpc:
    region: "{{ aws_vpc_region }}"
    cidr_block: "{{ aws_vpc_cidr_block }}"
    internet_gateway: true
    resource_tags: "{{ aws_vpc_resource_tags }}"
    wait: true
    subnets:
      - "{{ item[0] }}"
    route_tables:
      - subnets:
          - "{{ item[1].cidr }}"
        routes:
          - dest: 0.0.0.0/0
            gw: igw
